// ============================================================
//  Ampliação — Administração Geral · Estatística · LGPD
//  Questões autorais (conferidas) + flashcards. Cálculos resolvidos.
// ============================================================

QUESTOES.push(
  // ---------------- Administração Geral ----------------
  {
    id: 'ag-01', disciplina: 'adm-geral', assunto: 'Funções administrativas (PODC)',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'O processo administrativo é composto por quatro funções interligadas. A função responsável por monitorar o desempenho, comparar com o planejado e adotar ações corretivas é a de:',
    alternativas: ['Planejamento.', 'Organização.', 'Direção.', 'Controle.'],
    correta: 3,
    comentario: 'As funções administrativas (PODC) são: PLANEJAR (definir objetivos e meios), ORGANIZAR (alocar recursos e dividir o trabalho), DIRIGIR (liderar, motivar e coordenar pessoas) e CONTROLAR (medir o desempenho, comparar com o padrão e corrigir desvios). O monitoramento e a correção são do CONTROLE.',
    fonte: 'Teoria Geral da Administração — processo administrativo (Fayol)',
  },
  {
    id: 'ag-02', disciplina: 'adm-geral', assunto: 'Análise SWOT (FOFA)',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Na análise SWOT (FOFA), utilizada no planejamento estratégico, as oportunidades e as ameaças referem-se a fatores:',
    alternativas: [
      'internos da organização, controláveis por ela.',
      'externos à organização, do ambiente, não controláveis diretamente por ela.',
      'exclusivamente financeiros.',
      'relativos apenas aos concorrentes diretos.',
      'irrelevantes para a estratégia.',
    ],
    correta: 1,
    comentario: 'Na matriz SWOT: Forças (Strengths) e Fraquezas (Weaknesses) são fatores INTERNOS (controláveis pela organização); Oportunidades (Opportunities) e Ameaças (Threats) são fatores EXTERNOS/do ambiente (não controláveis diretamente). Em português, FOFA: Forças, Oportunidades, Fraquezas, Ameaças.',
    fonte: 'Planejamento estratégico — análise SWOT',
  },
  {
    id: 'ag-03', disciplina: 'adm-geral', assunto: 'Missão, visão e valores',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'No planejamento estratégico, o elemento que expressa a razão de ser da organização — o propósito que justifica sua existência no presente — é a:',
    alternativas: ['Visão.', 'Missão.', 'Meta.', 'Estratégia.', 'Política.'],
    correta: 1,
    comentario: 'A MISSÃO expressa a razão de ser / o propósito atual da organização (o que ela faz e para quem). A VISÃO é a situação futura desejada (onde se quer chegar). Os VALORES são os princípios e crenças que orientam o comportamento.',
    fonte: 'Planejamento estratégico — identidade organizacional',
  },
  {
    id: 'ag-04', disciplina: 'adm-geral', assunto: 'Ferramenta 5W2H',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'A ferramenta de gestão 5W2H é utilizada, essencialmente, para:',
    alternativas: [
      'medir o clima organizacional.',
      'elaborar planos de ação, detalhando o que será feito, por quê, onde, quando, por quem, como e quanto custará.',
      'avaliar o desempenho financeiro de longo prazo.',
      'priorizar riscos por probabilidade e impacto.',
      'desenhar o organograma da empresa.',
    ],
    correta: 1,
    comentario: 'O 5W2H estrutura planos de ação por meio de sete perguntas: What (o quê), Why (por quê), Where (onde), When (quando), Who (quem), How (como) e How much (quanto custa). É uma ferramenta simples de planejamento e checagem da execução.',
    fonte: 'Gestão da qualidade — ferramenta 5W2H',
  },
  {
    id: 'ag-05', disciplina: 'adm-geral', assunto: 'Matriz GUT',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'A Matriz GUT é uma ferramenta usada para priorizar problemas a partir de três critérios, que são:',
    alternativas: [
      'Gestão, Urgência e Tecnologia.',
      'Gravidade, Urgência e Tendência.',
      'Grau, Utilidade e Tempo.',
      'Ganho, Uso e Território.',
      'Gravidade, Utilidade e Técnica.',
    ],
    correta: 1,
    comentario: 'A Matriz GUT prioriza problemas combinando GRAVIDADE (impacto do problema), URGÊNCIA (prazo para agir) e TENDÊNCIA (se tende a piorar). Atribui-se nota de 1 a 5 a cada critério e multiplica-se (G × U × T); quanto maior o produto, maior a prioridade.',
    fonte: 'Gestão da qualidade — Matriz GUT',
  },
  {
    id: 'ag-06', disciplina: 'adm-geral', assunto: 'Eficiência, eficácia e efetividade',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Sobre os conceitos de desempenho na Administração, assinale a alternativa correta.',
    alternativas: [
      'Eficiência relaciona-se ao alcance dos resultados (fins), e eficácia ao uso dos recursos (meios).',
      'Eficiência é a boa utilização dos recursos (fazer certo/otimizar meios); eficácia é o alcance dos objetivos (fazer a coisa certa/resultados); efetividade é o impacto real e duradouro gerado.',
      'Efetividade e eficiência são sinônimos.',
      'Eficácia mede apenas o custo por unidade produzida.',
      'Efetividade ignora os resultados de médio e longo prazo.',
    ],
    correta: 1,
    comentario: 'EFICIÊNCIA = fazer certo, com o melhor uso dos recursos/meios (produtividade). EFICÁCIA = fazer a coisa certa, alcançando os objetivos/resultados. EFETIVIDADE = o impacto/transformação real e duradoura provocada (resultado que gera valor para a sociedade). Ex.: uma campanha pode ser eficiente e eficaz, mas só efetiva se mudar de fato a realidade.',
    fonte: 'Administração — desempenho (eficiência, eficácia, efetividade)',
  },

  // ---------------- Estatística ----------------
  {
    id: 'est-01', disciplina: 'estatistica', assunto: 'Média aritmética (cálculo)',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Considere o conjunto de valores: 4, 8, 6, 10 e 2. A média aritmética desse conjunto é:',
    alternativas: ['5.', '6.', '7.', '8.', '30.'],
    correta: 1,
    comentario: 'Média aritmética = soma dos valores ÷ quantidade = (4 + 8 + 6 + 10 + 2) ÷ 5 = 30 ÷ 5 = 6.',
    fonte: 'Estatística descritiva — medidas de posição',
  },
  {
    id: 'est-02', disciplina: 'estatistica', assunto: 'Mediana (cálculo)',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Para o conjunto de dados 3, 7, 2, 9 e 5, a mediana é:',
    alternativas: ['3.', '5.', '7.', '9.', '5,2.'],
    correta: 1,
    comentario: 'A mediana é o valor central dos dados ORDENADOS. Ordenando: 2, 3, 5, 7, 9. Como há 5 elementos (número ímpar), a mediana é o 3º valor = 5. (Se o número de elementos fosse par, seria a média dos dois centrais.)',
    fonte: 'Estatística descritiva — medidas de posição',
  },
  {
    id: 'est-03', disciplina: 'estatistica', assunto: 'Moda',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'No conjunto de valores 5, 7, 7, 8, 9, 7 e 10, a moda é:',
    alternativas: ['5.', '7.', '8.', '10.', 'Não há moda.'],
    correta: 1,
    comentario: 'A MODA é o valor que aparece com maior frequência. O valor 7 ocorre três vezes (a maior frequência), enquanto os demais ocorrem uma vez. Logo, a moda é 7. Um conjunto pode ser amodal (sem moda), unimodal, bimodal, etc.',
    fonte: 'Estatística descritiva — medidas de posição',
  },
  {
    id: 'est-04', disciplina: 'estatistica', assunto: 'Coeficiente de variação (cálculo)',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Uma distribuição tem média igual a 50 e desvio padrão igual a 5. O coeficiente de variação (CV) é:',
    alternativas: ['5%.', '10%.', '25%.', '45%.', '50%.'],
    correta: 1,
    comentario: 'O Coeficiente de Variação mede a dispersão RELATIVA: CV = (desvio padrão ÷ média) × 100 = (5 ÷ 50) × 100 = 10%. É útil para comparar a variabilidade de conjuntos com médias/unidades diferentes; quanto menor o CV, mais homogêneo o conjunto.',
    fonte: 'Estatística descritiva — medidas de dispersão',
  },
  {
    id: 'est-05', disciplina: 'estatistica', assunto: 'Probabilidade básica',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Ao lançar um dado honesto de seis faces, a probabilidade de sair um número par é:',
    alternativas: ['1/6.', '1/3.', '1/2.', '2/3.', '1.'],
    correta: 2,
    comentario: 'Probabilidade = casos favoráveis ÷ casos possíveis. Os números pares em um dado são {2, 4, 6} = 3 casos favoráveis, em 6 possíveis. P = 3/6 = 1/2 = 50%.',
    fonte: 'Probabilidade — espaço amostral equiprovável',
  },
  {
    id: 'est-06', disciplina: 'estatistica', assunto: 'Tipos de amostragem',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'A técnica de amostragem em que a população é dividida em subgrupos homogêneos (estratos) e, de cada um, seleciona-se uma amostra proporcional é a amostragem:',
    alternativas: ['aleatória simples.', 'sistemática.', 'estratificada.', 'por conglomerados (clusters).', 'por conveniência.'],
    correta: 2,
    comentario: 'Na amostragem ESTRATIFICADA, a população é dividida em estratos internamente homogêneos (ex.: por faixa de renda, região) e amostra-se cada um, geralmente de forma proporcional. Na SISTEMÁTICA, seleciona-se a cada k elementos; na ALEATÓRIA SIMPLES, todos têm igual chance; nos CONGLOMERADOS, sorteiam-se grupos inteiros.',
    fonte: 'Estatística — técnicas de amostragem',
  },

  // ---------------- LGPD ----------------
  {
    id: 'lgpd-01', disciplina: 'lgpd', assunto: 'Conceitos — dado pessoal e sensível',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'De acordo com a LGPD (Lei nº 13.709/2018), assinale a alternativa correta.',
    alternativas: [
      'Dado pessoal e dado pessoal sensível são conceitos idênticos.',
      'Dado pessoal é a informação relacionada a pessoa natural identificada ou identificável; dado pessoal sensível é a espécie qualificada que envolve, por exemplo, origem racial, convicção religiosa, dado de saúde, biometria ou orientação sexual.',
      'A LGPD protege dados de pessoas jurídicas.',
      'Dado anonimizado é sempre considerado dado pessoal.',
      'A LGPD só se aplica a dados tratados em meio digital.',
    ],
    correta: 1,
    comentario: 'Art. 5º da LGPD: DADO PESSOAL é a informação relacionada a pessoa natural identificada ou identificável. DADO SENSÍVEL é a espécie que envolve origem racial/étnica, convicção religiosa, opinião política, filiação sindical, dado referente à saúde ou à vida sexual, dado genético ou biométrico — recebe proteção reforçada. A LGPD protege pessoas NATURAIS e aplica-se a tratamentos em meio físico ou digital; dado efetivamente anonimizado não é dado pessoal.',
    fonte: 'Lei nº 13.709/2018, art. 5º',
  },
  {
    id: 'lgpd-02', disciplina: 'lgpd', assunto: 'Agentes de tratamento',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Na LGPD, a pessoa a quem compete as decisões referentes ao tratamento de dados pessoais é o(a):',
    alternativas: [
      'operador.',
      'controlador.',
      'encarregado (DPO).',
      'titular.',
      'autoridade nacional.',
    ],
    correta: 1,
    comentario: 'CONTROLADOR: a quem competem as DECISÕES sobre o tratamento. OPERADOR: realiza o tratamento em nome do controlador. ENCARREGADO (DPO): canal de comunicação entre controlador, titulares e a ANPD. TITULAR: a pessoa natural a quem se referem os dados (art. 5º, VI a IX).',
    fonte: 'Lei nº 13.709/2018, art. 5º, VI a IX',
  },
  {
    id: 'lgpd-03', disciplina: 'lgpd', assunto: 'Tratamento pelo Poder Público',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'Sobre o tratamento de dados pessoais pela Administração Pública (inclusive a tributária), assinale a alternativa correta.',
    alternativas: [
      'É vedado ao Poder Público tratar dados pessoais.',
      'O tratamento deve ter finalidade pública, na persecução do interesse público, para executar competências legais ou cumprir atribuições do serviço público, informada a hipótese de tratamento.',
      'O consentimento do titular é sempre obrigatório para o Poder Público.',
      'Os dados coletados pela Administração podem ser usados para qualquer finalidade, sem limites.',
      'A Administração pode transferir dados a entidades privadas livremente, sem qualquer condição.',
    ],
    correta: 1,
    comentario: 'Art. 23 da LGPD: o Poder Público pode tratar dados para o atendimento de sua FINALIDADE PÚBLICA, na persecução do interesse público, com o objetivo de executar competências legais ou cumprir atribuições do serviço público — dispensado o consentimento, mas vinculado à finalidade informada, à necessidade e às demais regras da lei. Não é tratamento ilimitado nem livre compartilhamento.',
    fonte: 'Lei nº 13.709/2018, arts. 23 a 30',
  },
  {
    id: 'lgpd-04', disciplina: 'lgpd', assunto: 'Direitos do titular',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'São direitos do titular dos dados assegurados pela LGPD, EXCETO:',
    alternativas: [
      'confirmação da existência de tratamento e acesso aos dados.',
      'correção de dados incompletos, inexatos ou desatualizados.',
      'eliminação dos dados tratados com consentimento, ressalvadas hipóteses legais de conservação.',
      'portabilidade dos dados a outro fornecedor, mediante requisição.',
      'a fixação unilateral das alíquotas dos tributos incidentes sobre o controlador.',
    ],
    correta: 4,
    comentario: 'O art. 18 da LGPD assegura ao titular, entre outros: confirmação e acesso; correção; anonimização, bloqueio ou eliminação de dados desnecessários/excessivos; portabilidade; eliminação dos dados tratados com consentimento; informação sobre compartilhamento; e revogação do consentimento. A "fixação de alíquotas" (letra E) nada tem a ver com direitos do titular — é matéria tributária.',
    fonte: 'Lei nº 13.709/2018, art. 18',
  },
  {
    id: 'lgpd-05', disciplina: 'lgpd', assunto: 'ANPD',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'A autoridade responsável por zelar, implementar e fiscalizar o cumprimento da LGPD em todo o território nacional é:',
    alternativas: [
      'a Receita Federal do Brasil.',
      'a Autoridade Nacional de Proteção de Dados (ANPD).',
      'o Ministério Público Federal.',
      'o Tribunal de Contas da União.',
      'o Banco Central.',
    ],
    correta: 1,
    comentario: 'A ANPD (Autoridade Nacional de Proteção de Dados) é o órgão responsável por zelar, implementar e fiscalizar o cumprimento da LGPD, editar normas e orientações, e aplicar sanções administrativas (arts. 55-A e seguintes). É a autoridade central em matéria de proteção de dados no país.',
    fonte: 'Lei nº 13.709/2018, arts. 55-A e 55-J',
  },
  {
    id: 'lgpd-06', disciplina: 'lgpd', assunto: 'Princípios do tratamento',
    banca: 'Autoral', ano: 2026, cargo: 'AFRM',
    enunciado: 'O princípio da LGPD segundo o qual o tratamento deve limitar-se ao mínimo necessário para a realização de suas finalidades, com abrangência dos dados pertinentes e não excessivos, é o da:',
    alternativas: ['finalidade.', 'adequação.', 'necessidade.', 'transparência.', 'segurança.'],
    correta: 2,
    comentario: 'Princípio da NECESSIDADE (art. 6º, III): limitação do tratamento ao mínimo necessário para as finalidades, com dados pertinentes, proporcionais e não excessivos. FINALIDADE = propósito legítimo e específico; ADEQUAÇÃO = compatibilidade com as finalidades informadas; TRANSPARÊNCIA = informações claras ao titular; SEGURANÇA = medidas de proteção.',
    fonte: 'Lei nº 13.709/2018, art. 6º',
  },
);

FLASHCARDS.push(
  { id: 'fag-1', disciplina: 'adm-geral', frente: 'Funções administrativas (PODC)?', verso: 'Planejar (objetivos/meios), Organizar (recursos/estrutura), Dirigir (liderar/coordenar pessoas), Controlar (medir e corrigir).' },
  { id: 'fag-2', disciplina: 'adm-geral', frente: 'SWOT (FOFA): o que é interno e externo?', verso: 'Internos (controláveis): Forças e Fraquezas. Externos (ambiente): Oportunidades e Ameaças.' },
  { id: 'fag-3', disciplina: 'adm-geral', frente: 'Missão x Visão x Valores?', verso: 'Missão = razão de existir (presente). Visão = onde quer chegar (futuro). Valores = princípios que orientam o comportamento.' },
  { id: 'fag-4', disciplina: 'adm-geral', frente: 'Matriz GUT: quais critérios?', verso: 'Gravidade × Urgência × Tendência (nota 1 a 5 cada). Maior produto = maior prioridade.' },
  { id: 'fag-5', disciplina: 'adm-geral', frente: '5W2H: o que significa?', verso: 'What, Why, Where, When, Who, How e How much — estrutura planos de ação (o quê, por quê, onde, quando, quem, como, quanto custa).' },
  { id: 'fag-6', disciplina: 'adm-geral', frente: 'Eficiência x Eficácia x Efetividade?', verso: 'Eficiência = usar bem os recursos (meios). Eficácia = atingir os objetivos (resultados). Efetividade = impacto real e duradouro.' },
  { id: 'fest-1', disciplina: 'estatistica', frente: 'Média, mediana e moda?', verso: 'Média = soma/n. Mediana = valor central (dados ordenados). Moda = valor mais frequente.' },
  { id: 'fest-2', disciplina: 'estatistica', frente: 'Coeficiente de variação (CV)?', verso: 'CV = (desvio padrão ÷ média) × 100. Mede dispersão RELATIVA; quanto menor, mais homogêneo.' },
  { id: 'fest-3', disciplina: 'estatistica', frente: 'Medidas de dispersão principais?', verso: 'Amplitude, variância, desvio padrão (raiz da variância) e coeficiente de variação. Medem o espalhamento dos dados.' },
  { id: 'fest-4', disciplina: 'estatistica', frente: 'Amostragem estratificada x conglomerados?', verso: 'Estratificada: divide em estratos HOMOGÊNEOS e amostra cada um. Conglomerados: sorteia GRUPOS inteiros (heterogêneos internamente).' },
  { id: 'flgpd-1', disciplina: 'lgpd', frente: 'Dado pessoal x dado sensível?', verso: 'Pessoal: relacionado a pessoa natural identificada/identificável. Sensível: origem racial, religião, saúde, biometria, vida sexual, etc. (proteção reforçada).' },
  { id: 'flgpd-2', disciplina: 'lgpd', frente: 'Controlador, operador e encarregado?', verso: 'Controlador: decide o tratamento. Operador: trata em nome do controlador. Encarregado (DPO): canal com titulares e ANPD.' },
  { id: 'flgpd-3', disciplina: 'lgpd', frente: 'Poder Público precisa de consentimento?', verso: 'Não: trata dados para finalidade pública / execução de competências legais (art. 23), sempre vinculado à finalidade e à necessidade.' },
  { id: 'flgpd-4', disciplina: 'lgpd', frente: 'Quem fiscaliza a LGPD?', verso: 'A ANPD (Autoridade Nacional de Proteção de Dados): zela, regula, fiscaliza e aplica sanções.' },
  { id: 'flgpd-5', disciplina: 'lgpd', frente: 'Princípio da necessidade (LGPD)?', verso: 'Tratar o MÍNIMO necessário à finalidade, com dados pertinentes e NÃO excessivos (art. 6º, III).' },
);
